import "@/styles/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/providers/ThemeProvider";
import Footer from "@/components/Footer";

const eina = localFont({
  src: [
    {
      path: "../../public/fonts/eina/Eina02-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/eina/Eina02-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/eina/Eina02-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-eina",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${eina.variable}`} suppressHydrationWarning>
      <body className="font-eina transition-[background-color] duration-300">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
